### ISSUE TITLE
Featured images

### ISSUE THREAD

**Issue by adisos** [robmiller/ruby-wpdb#22]
What about featured images?

**Comment by robmiller** [comment]
There isn't specific support for them yet; I'd welcome a patch. It would need to replicate things like `wp_get_attachment_url` as well as the necessary database stuff.

**Comment by parasquid** [comment]
So I found this in a Google search, and thought that I'd go and see what can be done (shouldn't be that hard right?)

HOLY SHIT. How do Wordpress developers work with this thing??!

Anyway, let me see what happens first: I get something out and send in a patch, or I give up and just use XMLRPC :P

**Comment by adis-io** [comment]
This SQL helped me:

```
 SELECT
        p1.*,
        wm2.meta_value
    FROM 
        wp_posts p1
    LEFT JOIN 
        wp_postmeta wm1
        ON (
            wm1.post_id = p1.id 
            AND wm1.meta_value IS NOT NULL
            AND wm1.meta_key = "_thumbnail_id"              
        )
    LEFT JOIN 
        wp_postmeta wm2
        ON (
            wm1.meta_value = wm2.post_id
            AND wm2.meta_key = "_wp_attached_file"
            AND wm2.meta_value IS NOT NULL  
        )
    WHERE
        p1.post_status="publish" 
        AND p1.post_type="post"
    ORDER BY 
        p1.post_date DESC
```

**Comment by parasquid** [comment]
Hahaha thanks! :)

**Comment by adis-io** [comment]
It's my `Post` model

```
class Post < WPDB::Post
    dataset_module do
      def default_scope
        filter(post_type: 'post', post_status: 'publish').reverse_order(:post_date)
      end

      def published
        filter(post_status: 'publish')
      end

      def with_featured
        left_outer_join(:main_postmeta, {
          :post_id => :main_posts__id,
          :mpm__meta_key => '_thumbnail_id'
        }, :table_alias => :mpm).
        left_outer_join(:main_postmeta, {
          :post_id => :mpm__meta_value,
          :mpm2__meta_key => '_wp_attachment_metadata'
        },  :table_alias => :mpm2).select_append(:mpm2__meta_value___metadata)
      end
    end

    set_dataset(self.default_scope)

    ALLOWED_COLUMNS = [:ID, :post_author, :post_date, :post_title, :post_excerpt, :post_name, :comment_count]

    def thumbnail size = nil
      if self[:metadata].present?
        metadata = PhpSerialization.load(self[:metadata])
        if size
          date = /(\d+\/\d+\/)/.match(metadata['file']).try(:[], 1)
          image = date + metadata['sizes'][size]['file']
        else
          image = metadata['file']
        end
      end
      image = image || get_default_image(size)
      URI.join(uploads_url, image).to_s
    end

    def get_default_image size = nil
      case size
      when 'thumb'
        "2014/12/sidebar-300x110.jpg"
      else
        "2014/12/sidebar.jpg"
      end
    end
  end
```

**Comment by parasquid** [comment]
Thanks again. I'm more familiar with ActiveRecord, so I'm learning a lot about how Sequel does scopes :)

@robmiller how do you want the attachment_url implemented? I'm thinking of a method called `#attachment_url` that returns the url of the attachment (thanks to @adisos code).

Also, I suggest common scopes e.g. `published` or `posts` (for excluding revisions) also be implemented, or at least a canonical way to implement them added to the documentation.

**Comment by adis-io** [comment]
By the way, I had to rewrite these models in activerecord, so I'm not using this gem now, but it helped me a lot.

**Comment by robmiller** [comment]
Off the top of my head, I'd expect it to work like:

```
post = WPDB::Post[42]
post.featured_image
# => a WPDB::Post object that points to the attachment
post.featured_image.attachment_url
# => the URL of this specific attachment
```

At this point, I'm thinking that we should probably do [single table inheritance](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/SingleTableInheritance.html) on the posts table so that what's returned from `featured_image` is a `WPDB::Attachment` (which extends `WPDB::Post`) and so that the `attachment_url` (or, I guess, just `url`) method is defined on `WPDB::Attachment` rather than `WPDB::Post`.

Implementing scopes is an excellent idea — I'll open a separate issue for that. I must confess, I've always done this with class methods on models and only learned about `dataset_module` from adisos's above post, so I've learned something too!

**Comment by parasquid** [comment]
Sounds great, my only issue with chaining like that is that featured_image might return a nil and so we have a lot of boilerplate code to make sure it isn't.

It's not like the scopes where it returns the self-modified object, so we're almost sure it won't return nil.

Or maybe we can return a WPDB::Null object that will return an empty string for any method called on it? Or get rid of the extra method call on featured_image and maybe just name the method featured_image_url

For WPDB::Attachment maybe we can implement it differently than STI. I'm not very experienced at Sequel, but we have something called polymorphic associations in ActiveRecord (see http://www.gotealeaf.com/blog/understanding-polymorphic-associations-in-rails)

My worry is that with STI we'll end up with a table that has a lot of fields that are nil because they're not used.

**Comment by robmiller** [comment]
Well, we needn't be worried about ending up with a table with any sort of fields, because we're bound by the database structure of WordPress: ruby-wpdb's motive is to let you access the schema of WordPress without modifying it in any way.

Single-table inheritance makes sense in this case because that's what the data is from the perspective of WordPress: lots of things go into the posts table that aren't posts per se. Some of them are very similar to posts, like pages (which have the `post_type` "page"); some of them are very different, like attachments (which have the `post_type` "attachment").

We'd just be modelling this existing structure by using STI, ensuring that an `Attachment` object is returned for posts of type `attachment`.
